apiVersion: v1
kind: Secret
metadata:
  name: mono-repo-development
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
stringData:
  type: git
  name: development
  url: https://github.com/mcconnellj/Mono-Repo.git
  targetRevision: development
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: minikube-cluster
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: cluster
# type: Opaque
# stringData:
#   name: minikube
#   server: https://kubernetes.default.svc
#   project: default
#   config: |
#     {
#       "tlsClientConfig": {
#         "insecure": true
#       }
#     }
