---
# Source: actualbudget/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-actualbudget
  labels:
    helm.sh/chart: actualbudget-1.8.0
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/instance: my-actualbudget
    app.kubernetes.io/version: "25.7.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: actualbudget/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-actualbudget
  labels:
    helm.sh/chart: actualbudget-1.8.0
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/instance: my-actualbudget
    app.kubernetes.io/version: "25.7.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5006
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/instance: my-actualbudget
---
# Source: actualbudget/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-actualbudget
  labels:
    helm.sh/chart: actualbudget-1.8.0
    app.kubernetes.io/name: actualbudget
    app.kubernetes.io/instance: my-actualbudget
    app.kubernetes.io/version: "25.7.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app.kubernetes.io/name: actualbudget
      app.kubernetes.io/instance: my-actualbudget
  template:
    metadata:
      labels:
        helm.sh/chart: actualbudget-1.8.0
        app.kubernetes.io/name: actualbudget
        app.kubernetes.io/instance: my-actualbudget
        app.kubernetes.io/version: "25.7.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: my-actualbudget
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: actualbudget
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          image: "actualbudget/actual-server:25.7.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: ACTUAL_PORT
              value: "5006"
            - name: ACTUAL_DATA_DIR
              value: /data
            - name: ACTUAL_SERVER_FILES
              value: /data/server-files
            - name: ACTUAL_USER_FILES
              value: /data/user-files
            - name: ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB
              value: "20"
            - name: ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB
              value: "50"
            - name: ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB
              value: "20"
            - name: ACTUAL_LOGIN_METHOD
              value: "password"
            - name: ACTUAL_ALLOWED_LOGIN_METHODS
              value: "password,header,openid"
          ports:
            - name: http
              containerPort: 5006
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
