k8sServiceHost: "172.17.0.3"
k8sServicePort: "6443"

kubeProxyReplacement: true

l2announcements:
  enabled: true

externalIPs:
  enabled: true

k8sClientRateLimit:
  qps: 50
  burst: 200

operator:
  replicas: 1
  rollOutPods: true

rollOutCiliumPods: true
