apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-instance-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
        generators:
        - git:
            repoURL: https://gitlab.com/your-name/your-repo.git
            revision: HEAD
            files:
            - path: "/applications/*/*.json"
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
                kubernetes.io/environment: '{{.path.basename}}'
  template:
    spec:
      project: default
      sources:
        - chart: '{{`{{ .chart.name }}`}}'
          repoURL: '{{`{{ .chart.repository }}`}}'
          targetRevision: '{{`{{ .chart.version }}`}}'
          helm:
            valueFiles:
              - $values/appset-helm-demo/components/{{ .Values.projectName }}/{{`{{ index .path.segments 3 }}`}}/{{`{{ index .path.segments 4 }}`}}/values.yaml
            parameters:
              - name: appName
                value: '{{ .Values.projectName }}'
        - repoURL: 'https://github.com/piomin/argocd-showcase.git'
          targetRevision: HEAD
          ref: values
      destination:
        name: {{.server}}
        namespace: argocd
        syncPolicy:
    automated:
      selfHeal: true
      prune: true