apiVersion: v1
kind: Secret
metadata:
  name: minikube-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: minikube
  server: https://127.0.0.1:8443